version: '2'
services:
  database:
    image: "mongo"
  redis:
    image: "redis"
  front:
    image: "front"
    ports:
      - "4200:80"
  back:
    image: "back"
    ports:
      - "8000:8000"
    depends_on:
      - database
      - redis